pheno_csv_key: hapmap_pheno_demo.csv
n_pcs: 3
covariates: gender Hare
out_prefix: test
outcome: height
outcome_is_binary: "FALSE"
pca_file: /commons-data/hapmap_test_pcair_pca.RData
relatedness_matrix_file: /commons-data/hapmap_test_pcrelate_pcrelate_Matrix.RData
genome_build: hg19
n_segments: 1
segment_length: 10000
gds_files: |-
  [
    "/commons-data/hapmap-ceu_chr1.gds",
    "/commons-data/hapmap-ceu_chr2.gds",
    "/commons-data/hapmap-ceu_chr3.gds",
    "/commons-data/hapmap-ceu_chr4.gds",
    "/commons-data/hapmap-ceu_chr5.gds",
    "/commons-data/hapmap-ceu_chr6.gds",
    "/commons-data/hapmap-ceu_chr7.gds",
    "/commons-data/hapmap-ceu_chr8.gds",
    "/commons-data/hapmap-ceu_chr9.gds",
    "/commons-data/hapmap-ceu_chr10.gds",
    "/commons-data/hapmap-ceu_chr11.gds",
    "/commons-data/hapmap-ceu_chr12.gds",
    "/commons-data/hapmap-ceu_chr13.gds",
    "/commons-data/hapmap-ceu_chr14.gds",
    "/commons-data/hapmap-ceu_chr15.gds",
    "/commons-data/hapmap-ceu_chr16.gds",
    "/commons-data/hapmap-ceu_chr17.gds",
    "/commons-data/hapmap-ceu_chr18.gds",
    "/commons-data/hapmap-ceu_chr19.gds",
    "/commons-data/hapmap-ceu_chr20.gds",
    "/commons-data/hapmap-ceu_chr21.gds",
    "/commons-data/hapmap-ceu_chr22.gds"
  ]
