apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: vadc-gwas-
  namespace: argo
  annotations:
    workflows.argoproj.io/version: ">= 3.1.0"
spec:
  entrypoint: null-model
  podGC:
    strategy: OnWorkflowSuccess
  ttlStrategy:
    secondsAfterCompletion: 300
  arguments:
    parameters:
      - name: phenotype_file
        description: Phenotype and covariates Rdata object.
        value: /commons-data/hapmap_pheno_demo.RData
      - name: n_pcs
        description: Number of PCs to include as covariates.
        default: 0
        value: 3 
      - name: covariates
        description: |-
          Names of columns phenotype_file containing covariates. Separate by spaces.
          e.g., `gender height healthy`
        value: gender Hare
      - name: out_prefix
        description: Prefix for files created by the workflow.
        default: genesis_vadc
        value: test
      - name: outcome
        description: Name of column in phenotype_file containing outcome variable.
        value: height
      - name: outcome_is_binary
        description: |-
          TRUE if outcome is a binary (case/control) variable;
          FALSE if outcome is a continuous variable.
        enum:
          - "TRUE"
          - "FALSE"
        default: "FALSE"
        value: "FALSE"
      - name: pca_file
        description: RData file with PCA results created by PC-AiR.
        value: /commons-data/hapmap_test_pcair_pca.RData
      - name: relatedness_matrix_file
        description: RData object with a kinship matrix.
        value: /commons-data/hapmap_test_pcrelate_pcrelate_Matrix.RData
      - name: genome_build
        description: Genome build
        enum:
          - "hg38"
          - "hg19"
        default: "hg19"
        value: "hg19"
      - name: n_segments
        description: Number of segments (overrides segment length).
        value: 1
      - name: segment_length
        description: Segment length in KB
        default: 10000
        value: 10000
      - name: gds_files
        description: Array of per-chromosome GDS files.
        value: '["/commons-data/hapmap-ceu_chr1.gds"]'

  volumes:
    - name: gateway
      persistentVolumeClaim:
        claimName: mariner-nfs-pvc
    - name: workdir
      emptyDir: {}

  templates:
    - name: null-model
      dag:
        tasks:
          - name: run-null-model
            template: run-null-model
            arguments:
              parameters:
                - name: n_pcs
                  value: "{{workflow.parameters.n_pcs}}"
                - name: covariates
                  value: "{{workflow.parameters.covariates}}"
                - name: out_prefix
                  value: "{{workflow.parameters.out_prefix}}_null_model"
                - name: outcome
                  value: "{{workflow.parameters.outcome}}"
                - name: outcome_is_binary
                  value: "{{workflow.parameters.outcome_is_binary}}"
                - name: pca_file
                  value: "{{workflow.parameters.pca_file}}"
                - name: phenotype_file
                  value: "{{workflow.parameters.phenotype_file}}"
                - name: relatedness_matrix_file
                  value: "{{workflow.parameters.relatedness_matrix_file}}"

          - name: define-segments
            template: define-segments
            arguments:
              parameters:
                - name: genome_build
                  value: "{{workflow.parameters.genome_build}}"
                - name: n_segments
                  value: "{{workflow.parameters.n_segments}}"
                - name: segment_length
                  value: "{{workflow.parameters.segment_length}}"

          - name: split-filename
            template: split-filename
            arguments:
              parameters:
                - name: gds_file
                  value: "{{=map(jsonpath(workflow.parameters.gds_files, '$'), {#})[0]}}"

          - name: filter-segments
            template: filter-segments
            dependencies: [define-segments, split-filename]
            arguments:
              parameters:
                - name: file_prefix
                  value: "{{=jsonpath(tasks.split-filename.outputs.result, '$.file_prefix')}}"
                - name: file_suffix
                  value: "{{=jsonpath(tasks.split-filename.outputs.result, '$.file_suffix')}}"
                - name: gds_filenames
                  value: "{{workflow.parameters.gds_files}}"
              artifacts:
                - name: segment_file
                  from: "{{tasks.define-segments.outputs.artifacts.segment_file}}"

    - name: run-null-model
      inputs:
        parameters:
          - name: n_pcs
          - name: covariates
          - name: out_prefix
          - name: outcome
          - name: outcome_is_binary
          - name: pca_file
          - name: phenotype_file
          - name: relatedness_matrix_file

      script:
        image: uwgac/topmed-master:2.12.0
        command: [bash]
        source: |
          cd /mnt/vol
          echo "out_prefix {{inputs.parameters.out_prefix}}" > null_model.config
          echo "phenotype_file {{inputs.parameters.phenotype_file}}" >> null_model.config
          echo "outcome {{inputs.parameters.outcome}}" >> null_model.config
          echo "binary {{inputs.parameters.outcome_is_binary}}" >> null_model.config
          echo "n_pcs {{inputs.parameters.n_pcs}}" >> null_model.config
          echo "pca_file {{inputs.parameters.pca_file}}" >> null_model.config
          echo "relatedness_matrix_file {{inputs.parameters.relatedness_matrix_file}}" >> null_model.config
          echo "covariates \"{{inputs.parameters.covariates}}\"" >> null_model.config
          echo "out_phenotype_file {{inputs.parameters.out_prefix}}_phenotypes.Rdata" >> null_model.config

          set -xe
          cat null_model.config

          Rscript /usr/local/analysis_pipeline/R/null_model.R null_model.config
          Rscript /usr/local/analysis_pipeline/R/null_model_report.R null_model.config --version 2.12.0
          ls -al

          DATADIR={{inputs.parameters.out_prefix}}_datadir
          mkdir $DATADIR
          mv {{inputs.parameters.out_prefix}}*.RData $DATADIR/

          REPORTDIR={{inputs.parameters.out_prefix}}_reports
          mkdir $REPORTDIR
          mv *.html $REPORTDIR/
          mv *.Rmd $REPORTDIR/

        volumeMounts:
          - name: workdir
            mountPath: /mnt/vol
          - name: gateway
            mountPath: /commons-data

      outputs:
        artifacts:
          - name: null_model_directory
            path: "/mnt/vol/{{inputs.parameters.out_prefix}}_datadir"
            archive:
              none: {}
            s3:
              key: "{{inputs.parameters.out_prefix}}_datadir"
          - name: null_model_phenotype
            path: "/mnt/vol/{{inputs.parameters.out_prefix}}_phenotypes.Rdata"
            archive:
              none: {}
            s3:
              key: "{{inputs.parameters.out_prefix}}_phenotypes.Rdata"
          - name: null_model_report_directory
            path: "/mnt/vol/{{inputs.parameters.out_prefix}}_reports"
            archive:
              none: {}
            s3:
              key: "{{inputs.parameters.out_prefix}}_reports"

    - name: define-segments
      inputs:
        parameters:
          - name: genome_build
          - name: n_segments
          - name: segment_length

      script:
        image: uwgac/topmed-master:2.12.0
        command: [bash]
        source: |
          cd /mnt/vol
          echo "genome_build {{inputs.parameters.genome_build}}" > define_segments.config
          echo "out_file segments.txt" >> define_segments.config

          Rscript /usr/local/analysis_pipeline/R/define_segments.R \
          define_segments.config \
          --segment_length {{inputs.parameters.segment_length}} \
          --n_segments {{inputs.parameters.n_segments}}

        volumeMounts:
          - name: workdir
            mountPath: /mnt/vol

      outputs:
        artifacts:
          - name: segment_file
            path: "/mnt/vol/segments.txt"
            archive:
              none: {}
            s3:
              key: segments.txt

    - name: split-filename
      inputs:
        parameters:
          - name: gds_file
      script:
        image: python:3.7
        command: [python3]
        source: |
          import json
          import os

          gds_file = "{{inputs.parameters.gds_file}}"
          bname = os.path.basename(gds_file)
          pfx = bname.split("chr")[0] + 'chr'
          sfx = "." + ".".join(bname.split("chr")[1].split(".")[1:])
          dat = {"file_prefix": pfx, "file_suffix": sfx}
          print(json.dumps(dat))

    - name: filter-segments
      inputs:
        parameters:
          - name: gds_filenames
          - name: file_prefix
          - name: file_suffix
        artifacts:
          - name: segment_file
            path: "/mnt/vol/segments.txt"
      script:
        image: python:3.7
        command: [python3]
        source: |
          import json
          import os

          gds_files = set("{{= join \",\" .inputs.parameters.gds_filenames}}".split(","))
          file_prefix = "{{inputs.parameters.file_prefix}}"
          file_suffix = "{{inputs.parameters.file_suffix}}"
          segments_file = "{{inputs.artifacts.segment_file.path}}"

          chromosomes_present = set()
          segments = []
          with open(segments_file, "rt") as f:
              for n, line in enumerate(f.readlines()):
                  chrom = line.split()[0]
                  if file_prefix + chrom + file_suffix in gds_files:
                      chromosomes_present.add(chrom)
                      segments += [n]

          dat = {
            "chromosomes": list(chromosomes_present),
            "segments": segments
          }
          print(json.dump(dat))
