apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: vadc-gwas-
spec:
  entrypoint: null-model
  podGC:
    strategy: OnWorkflowSuccess
  arguments:
    parameters:
      - name: phenotype_file
        description: Phenotype and covariates Rdata object.
        value: /commons-data/hapmap_pheno_demo.RData
      - name: n_pcs
        description: Number of PCs to include as covariates.
        default: 0
        value: 3 
      - name: covariates
        description: |-
          Names of columns phenotype_file containing covariates. Separate by spaces.
          e.g., `gender height healthy`
        value: gender Hare
      - name: out_prefix
        description: Prefix for files created by the workflow.
        default: genesis_vadc
        value: test
      - name: outcome
        description: Name of column in phenotype_file containing outcome variable.
        value: height
      - name: outcome_is_binary
        description: |-
          TRUE if outcome is a binary (case/control) variable;
          FALSE if outcome is a continuous variable.
        enum:
          - "TRUE"
          - "FALSE"
        default: "FALSE"
        value: "FALSE"
      - name: pca_file
        description: RData file with PCA results created by PC-AiR.
        value: /commons-data/hapmap_test_pcair_pca.RData
      - name: relatedness_matrix_file
        description: RData object with a kinship matrix.
        value: /commons-data/hapmap_test_pcrelate_pcrelate_Matrix.RData
      - name: genome_build
        description: Genome build
        enum:
          - "hg38"
          - "hg19"
        default: "hg19"
        value: "hg19"
      - name: n_segments
        description: Number of segments (overrides segment length).
        value: 1
      - name: segment_length
        description: Segment length in KB
        default: 10000
        value: 10000

  volumes:
    - name: gateway
      persistentVolumeClaim:
        claimName: mariner-nfs-pvc
    - name: workdir
      emptyDir: {}

  templates:
    - name: null-model
      dag:
        tasks:
          - name: run-null-model
            template: run-null-model
            arguments:
              parameters:
                - name: n_pcs
                  value: "{{workflow.parameters.n_pcs}}"
                - name: covariates
                  value: "{{workflow.parameters.covariates}}"
                - name: out_prefix
                  value: "{{workflow.parameters.out_prefix}}_null_model"
                - name: outcome
                  value: "{{workflow.parameters.outcome}}"
                - name: outcome_is_binary
                  value: "{{workflow.parameters.outcome_is_binary}}"
                - name: pca_file
                  value: "{{workflow.parameters.pca_file}}"
                - name: phenotype_file
                  value: "{{workflow.parameters.phenotype_file}}"
                - name: relatedness_matrix_file
                  value: "{{workflow.parameters.relatedness_matrix_file}}"
    - name: run-null-model
      inputs:
        parameters:
          - name: n_pcs
          - name: covariates
          - name: out_prefix
          - name: outcome
          - name: outcome_is_binary
          - name: pca_file
          - name: phenotype_file
          - name: relatedness_matrix_file
      script:
        image: uwgac/topmed-master:2.12.0
        command: [bash]
        source: |
          cd /mnt/vol
          echo "out_prefix {{inputs.parameters.out_prefix}}" > null_model.config
          echo "phenotype_file {{inputs.parameters.phenotype_file}}" >> null_model.config
          echo "outcome {{inputs.parameters.outcome}}" >> null_model.config
          echo "binary {{inputs.parameters.outcome_is_binary}}" >> null_model.config
          echo "n_pcs {{inputs.parameters.n_pcs}}" >> null_model.config
          echo "pca_file {{inputs.parameters.pca_file}}" >> null_model.config
          echo "relatedness_matrix_file {{inputs.parameters.relatedness_matrix_file}}" >> null_model.config
          echo "covariates \"{{inputs.parameters.covariates}}\"" >> null_model.config
          echo "out_phenotype_file {{inputs.parameters.out_prefix}}_phenotypes.Rdata" >> null_model.config

          set -xe
          cat null_model.config

          Rscript /usr/local/analysis_pipeline/R/null_model.R null_model.config
          Rscript /usr/local/analysis_pipeline/R/null_model_report.R null_model.config --version 2.12.0
          ls -al

          DATADIR={{inputs.parameters.out_prefix}}_datadir
          mkdir $DATADIR
          mv {{inputs.parameters.out_prefix}}*.RData $DATADIR/

          REPORTDIR={{inputs.parameters.out_prefix}}_reports
          mkdir $REPORTDIR
          mv *.html $REPORTDIR/
          mv *.Rmd $REPORTDIR/

        volumeMounts:
          - name: workdir
            mountPath: /mnt/vol
          - name: gateway
            mountPath: /commons-data

      outputs:
        artifacts:
          - name: null_model_directory
            path: "/mnt/vol/{{inputs.parameters.out_prefix}}_datadir"
            archive:
              none: {}
            s3:
              key: "{{inputs.parameters.out_prefix}}_datadir"
          - name: null_model_phenotype
            path: "/mnt/vol/{{inputs.parameters.out_prefix}}_phenotypes.Rdata"
            archive:
              none: {}
            s3:
              key: "{{inputs.parameters.out_prefix}}_phenotypes.Rdata"
          - name: null_model_report_directory
            path: "/mnt/vol/{{inputs.parameters.out_prefix}}_reports"
            archive:
              none: {}
            s3:
              key: "{{inputs.parameters.out_prefix}}_reports"
