apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: test-ld-
  namespace: argo
  annotations:
    workflows.argoproj.io/version: ">= 3.2.0"
    workflow_name: "test"
  labels:
    workflows.argoproj.io/archive-strategy: "true"
    gen3username: "user-fan1-40uchicago-2eedu"
    # team_project /gwas_projects/Uchicago
    gen3teamproject: "2f677761735f70726f6a656374732f556368696361676f"  #pragma: allowlist secret
spec:
  entrypoint: ld-analysis
  podGC:
    strategy: OnPodCompletion
  nodeSelector:
    role: "{{workflow.name}}"
  tolerations:
    - key: "role"
      operator: "Equal"
      value: "{{workflow.name}}"
      effect: "NoSchedule"
  podMetadata:
    labels:
      gen3username: "user-fan1-40uchicago-2eedu"
    annotations:
      gen3username: "fan1@uchicago.edu"
  arguments:
    parameters:
      - name: template_version
        value: ld-analysis-workflow
      - name: internal_api_env
        value: default
      - name: source_id
        value: 2
      - name: workflow-name
        value: "gwas-workflow-0873757820"   # gwas workflow id
      - name: chr
        value: 1                 # Chromosome to analyze
      - name: start
        value: 109810000        # Start position in base pairs
      - name: stop
        value: 109820000    # Stop position in base pairs
      - name: out_prefix
        value: vadc_ld
      - name: team_project
        value: "/gwas_projects/Uchicago"
      - name: gds_files
        value: |-
          [
            "/commons-data/gds/chr1.merged.vcf.gz.gds",
            "/commons-data/gds/chr2.merged.vcf.gz.gds",
            "/commons-data/gds/chr3.merged.vcf.gz.gds",
            "/commons-data/gds/chr4.merged.vcf.gz.gds",
            "/commons-data/gds/chr5.merged.vcf.gz.gds",
            "/commons-data/gds/chr6.merged.vcf.gz.gds",
            "/commons-data/gds/chr7.merged.vcf.gz.gds",
            "/commons-data/gds/chr8.merged.vcf.gz.gds",
            "/commons-data/gds/chr9.merged.vcf.gz.gds",
            "/commons-data/gds/chr10.merged.vcf.gz.gds",
            "/commons-data/gds/chr11.merged.vcf.gz.gds",
            "/commons-data/gds/chr12.merged.vcf.gz.gds",
            "/commons-data/gds/chr13.merged.vcf.gz.gds",
            "/commons-data/gds/chr14.merged.vcf.gz.gds",
            "/commons-data/gds/chr15.merged.vcf.gz.gds",
            "/commons-data/gds/chr16.merged.vcf.gz.gds",
            "/commons-data/gds/chr17.merged.vcf.gz.gds",
            "/commons-data/gds/chr18.merged.vcf.gz.gds",
            "/commons-data/gds/chr19.merged.vcf.gz.gds",
            "/commons-data/gds/chr20.merged.vcf.gz.gds",
            "/commons-data/gds/chr21.merged.vcf.gz.gds",
            "/commons-data/gds/chr22.merged.vcf.gz.gds",
            "/commons-data/gds/chrX.merged.vcf.gz.gds"
          ]
  volumes:
    - name: gateway
      persistentVolumeClaim:
        claimName: vhdcprod-input-data-bucket-claim
    - name: workdir
      emptyDir:
        sizeLimit: "100Gi"
  workflowTemplateRef:
    name: ld-analysis-workflow
